import { StyleSheet } from 'react-native';

export const RequestCardStyles = StyleSheet.create({
  cardContainer: {
    backgroundColor: '#001a4d',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.22,
    shadowRadius: 4,
    width: '100%',
    minHeight: 100,
  },
  leftSection: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  avatarWrapper: {
    width: 55,
    height: 55,
    borderRadius: 27.5,
    backgroundColor: '#ffffff',
    marginRight: 14,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  infoContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  clientName: {
    fontSize: 18,
    fontWeight: '800',
    color: '#ffffff',
    marginBottom: 4,
  },
  metaText: {
    fontSize: 13,
    color: '#e2e8f0',
    marginTop: 2,
    fontWeight: '500',
  },
  timeTag: {
    position: 'absolute',
    top: 10,
    right: 16,
    fontSize: 10,
    color: '#ffffff',
    fontWeight: '600',
    opacity: 0.8,
  },
  detailsButton: {
    backgroundColor: '#ffffff',
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 20,
    marginLeft: 10,
  },
  detailsButtonText: {
    color: '#001a4d',
    fontSize: 12,
    fontWeight: '800',
  },
  statusBadge: {
    position: 'absolute',
    bottom: 10,
    right: 16,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: '#e2e8f0',
  },
  statusText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#001a4d',
  },
});
